name: keyantong_Auto_login
on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *"
jobs:
  Auto_sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: .github/workflows/requirements.txt

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Sign
        run: python Auto_sign_Keyantong.py
env:
  pass_dict: ${{ secrets.PASS_DICT }}
