name: keyantong_Auto_login
on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *"
jobs:
  Auto_sign:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.2'
      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r .github/workflows/requirements.txt
      - name: Sign
        run: |
          python3 Auto_sign_Keyantong.py
env:
  pass_dict: ${{ secrets.PASS_DICT }}

