name: keyantong_Auto_login
on:
  schedule:
    - cron: "00 21 * * *"
jobs:
  Auto_sign:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.2'
      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Chekin
        run: |
          python3 ./Auto_sign_Keyantong.py
env:
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}

